USE empresa;

SELECT F.Pnome, F.Unome, F.Endereco
FROM FUNCIONARIO AS F
INNER JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
WHERE D.Dnome = 'Pesquisa';

SELECT F.Pnome
FROM FUNCIONARIO AS F
INNER JOIN TRABALHA_EM AS T
ON F.Cpf = T.Fcpf
INNER JOIN PROJETO AS P
ON T.Pnr = P.Projnumero
WHERE P.Projnome = 'ProdutoX';

SELECT P.Projnumero, D.Dnumero, F.Unome, F.Endereco, F.Datanasc
FROM PROJETO AS P
INNER JOIN DEPARTAMENTO AS D
ON P.Dnum = D.Dnumero
INNER JOIN FUNCIONARIO AS F
ON D.Cpf_gerente = F.Cpf
WHERE P.Projlocal = 'Mauá'

SELECT F.Unome AS F_SOBRENOME, S.Unome AS S_SOBRENOME
FROM FUNCIONARIO AS F
LEFT JOIN FUNCIONARIO AS S
ON S.Cpf = F.Cpf_supervisor

SELECT D.Dnome
FROM DEPARTAMENTO AS D
LEFT JOIN FUNCIONARIO AS F
ON D.Dnumero = F.Dnr
WHERE F.Cpf IS NULL;

SELECT D.Dnome
FROM FUNCIONARIO AS F
RIGHT JOIN DEPARTAMENTO AS D
ON D.Dnumero = F.Dnr
WHERE F.Cpf IS NULL;

SELECT *
FROM FUNCIONARIO AS F
FULL JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero

SELECT F.Pnome, F.Datanasc
FROM FUNCIONARIO AS F
UNION
SELECT D.Nome_dependente, D.Datanasc
FROM DEPENDENTE AS D

SELECT L.Dlocal
FROM LOCALIZACAO_DEP AS L
UNION ALL
SELECT P.Projlocal
FROM PROJETO AS P

SELECT F.Pnome
FROM FUNCIONARIO AS F
WHERE F.Cpf IN (SELECT F.Cpf
			    FROM FUNCIONARIO AS F
			    EXCEPT
			    SELECT D.Cpf_gerente
			    FROM DEPARTAMENTO AS D)

SELECT F.PNOME
FROM FUNCIONARIO AS F
WHERE F.Cpf IN (
				SELECT F.Cpf
				FROM FUNCIONARIO AS F
				INTERSECT
				SELECT D.Cpf_gerente
				FROM DEPARTAMENTO AS D);

SELECT COUNT(F.Pnome) AS 'QUANT_FUNC_POR_DEPARTAMENTO'
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
GROUP BY D.Dnumero

SELECT SUM(F.Salario) AS 'SALARIO_POR_DEPARTAMENTO'
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
GROUP BY D.Dnumero

SELECT AVG(T.Horas) AS 'MEDIA_HORAS'
FROM TRABALHA_EM AS T
JOIN PROJETO AS P
ON T.Pnr = P.Projnumero
GROUP BY P.Projnome

SELECT COUNT(F.SEXO)
FROM FUNCIONARIO AS F
GROUP BY F.Sexo

SELECT MAX(F.SALARIO)
FROM FUNCIONARIO AS F
JOIN DEPARTAMENTO AS D
ON D.Dnumero = F.Dnr
GROUP BY (D.Dnome)

SELECT COUNT(P.Projlocal) AS 'NUMERO_PROJETOS_LOCAL'
FROM PROJETO AS P
GROUP BY (P.Projlocal)

SELECT D.Dnome AS 'DEPARTAMENTO', COUNT(F.Cpf) AS 'QUANTIDADE'
FROM DEPARTAMENTO AS D
JOIN FUNCIONARIO AS F
ON D.Dnumero = F.Dnr
GROUP BY D.Dnome
HAVING COUNT(F.CPF) > 3

SELECT P.Projnome
FROM PROJETO AS P
JOIN TRABALHA_EM AS T
ON T.Pnr = P.Projnumero
GROUP BY P.Projnome
HAVING sum(T.Horas) >= 50

SELECT *
FROM FUNCIONARIO AS F
WHERE EXISTS(SELECT 1 FROM DEPARTAMENTO AS D WHERE D.Cpf_gerente = F.Cpf)