# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O0ijupr7m6X1kbuHYL7dgRjv_M2-UdsP
"""

# Guilherme da Silva Scher
# Ciência da Computação

usuarios = [
    {"tipo": "aluno", "matricula": "A001", "historico_emprestimos": []},
    {"tipo": "professor", "matricula": "P001", "historico_emprestimos": []},
    {"tipo": "funcionario", "matricula": "F001", "historico_emprestimos": []}
]

livros = [
    {"isbn": "12345", "titulo": "Python para Iniciantes", "disponivel": True, "localizacao": "Estante A", "prazo_devolucao": None},
    {"isbn": "67890", "titulo": "Modelagem e Simulação", "disponivel": True, "localizacao": "Estante B", "prazo_devolucao": None}
]

bibliotecarios = [
    {"nome": "João", "turno": "manhã", "especializacao": None},
    {"nome": "Maria", "turno": "tarde", "especializacao": None}
]

print("Lista inicial de usuários:")
for u in usuarios:
    print(u)
print()

print("Lista inicial de livros:")
for l in livros:
    print(l)
print()

print("Lista inicial de bibliotecários:")
for b in bibliotecarios:
    print(b)
print()

emprestimos_ativos = {}

def encontrar_usuario(matricula):
    for usuario in usuarios:
        if usuario["matricula"] == matricula:
            return usuario
    return None

def encontrar_livro(isbn):
    for livro in livros:
        if livro["isbn"] == isbn:
            return livro
    return None

def emprestar_livro(matricula_usuario, isbn_livro):
    usuario = encontrar_usuario(matricula_usuario)
    livro = encontrar_livro(isbn_livro)

    if usuario is None:
        print(f"Usuário {matricula_usuario} não encontrado.")
        return
    if livro is None:
        print(f"Livro ISBN {isbn_livro} não encontrado.")
        return
    if not livro["disponivel"]:
        print(f"Livro '{livro['titulo']}' não está disponível no momento.")
        return

    livro["disponivel"] = False
    usuario["historico_emprestimos"].append(isbn_livro)
    emprestimos_ativos[isbn_livro] = matricula_usuario

    print(f"Livro '{livro['titulo']}' emprestado para {usuario['tipo']} {usuario['matricula']}")

def devolver_livro(matricula_usuario, isbn_livro):
    usuario = encontrar_usuario(matricula_usuario)
    livro = encontrar_livro(isbn_livro)

    if usuario is None or livro is None:
        print(f"Erro na devolução: usuário ou livro não encontrado.")
        return
    if isbn_livro not in emprestimos_ativos:
        print(f"O livro '{livro['titulo']}' não está registrado como emprestado.")
        return
    if emprestimos_ativos[isbn_livro] != matricula_usuario:
        print(f"O livro '{livro['titulo']}' não foi emprestado para {usuario['tipo']} {usuario['matricula']}.")
        return

    livro["disponivel"] = True
    del emprestimos_ativos[isbn_livro]

    print(f"Livro '{livro['titulo']}' devolvido por {usuario['tipo']} {usuario['matricula']}")

print("\n--- Início da Simulação da Biblioteca ---")
emprestar_livro("A001", "12345")
emprestar_livro("P001", "67890")
emprestar_livro("A001", "67890")
devolver_livro("A001", "12345")
emprestar_livro("F001", "12345")

print("--- Estado Final da Simulação ---")

print("\nLista dos livros com seus status:")
for livro in livros:
    status = "Disponível" if livro["disponivel"] else "Emprestado"
    print(f"- {livro['titulo']} (ISBN: {livro['isbn']}): {status}")

print("\nLista dos usuários com seus históricos de empréstimos:")
for usuario in usuarios:
    print(f"- {usuario['tipo']} {usuario['matricula']}: Empréstimos: {usuario['historico_emprestimos']}")

print("\nLista dos empréstimos ativos:")
for isbn, matricula in emprestimos_ativos.items():
    livro = encontrar_livro(isbn)
    usuario = encontrar_usuario(matricula)
    print(f"- Livro: '{livro['titulo']}' (ISBN: {isbn}) emprestado para {usuario['tipo']} (Matrícula: {matricula})")

print("\nSimulação finalizada.")

