# -*- coding: utf-8 -*-
"""aula10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o6au6S1YsoqLHKQm5kjoNCuRs76vlcln
"""

# -*- coding: utf-8 -*-
"""
Calculadora mínima de Erlang C (P(wait)) em M/M/c

Símbolos e fórmulas (todas no contexto M/M/c):
- λ (lambda): taxa de chegadas (clientes por unidade de tempo)
- μ (mi): taxa de atendimento de CADA servidor (clientes por unidade de tempo)
- c: número de servidores idênticos

Derivadas:
- a = λ/μ  (Erlangs)  → tráfego oferecido (carga média ofertada ao sistema)
- ρ = a/c = λ/(c μ)   → utilização média por servidor (0 < ρ < 1 para regime estável)

Fórmula de Erlang C (probabilidade de esperar na fila):
            (a^c / c!) * (c / (c − a))
P(wait) = ---------------------------------------------
          Σ_{n=0}^{c−1} (a^n / n!)  +  (a^c / c!) * (c / (c − a))

Observações:
- Estabilidade prática: a < c  (se a ≥ c, a fila “explode” e P(wait) → 1).
- Unidades de tempo em Wq e W são as mesmas usadas em λ e μ (min, h, ...).

A partir de P(wait), demais métricas (opcionais, mostradas aqui para referência):
- Wq = P(wait) / (c μ − λ)               (tempo médio de espera na fila)
- Lq = λ * Wq                             (número médio na fila — Little)
- W  = Wq + 1/μ                           (tempo médio no sistema)
- L  = λ * W                              (número médio no sistema — Little)

"""

# Guilherme da Silva Scher

from math import factorial

def erlang_c(a: float, c: int) -> float:
    """Retorna P(wait) dado o tráfego oferecido a=λ/μ (Erlangs) e c servidores.
    Observação: para estabilidade prática, é necessário a < c.
    """
    if a < 0 or c <= 0:
        raise ValueError("'a' deve ser >= 0 e 'c' > 0.")
    if a >= c:
        return 1.0  # sistema instável: P(wait) tende a 1

    #Formula: P(wait) = [ (a^c / c!) ×(c / (c -a)) ] / [ Σ(a^n / n!) + (a^c / c!) ×(c / (c -a)) ]
    soma = sum((a**n) / factorial(n) for n in range(c))        # Σ_{n=0}^{c-1} a^n/n!
    termo = (a**c) / factorial(c) * (c / (c - a))              # (a^c/c!) * (c/(c-a))
    return termo / (soma + termo)

def calcular_ro(a: float, c: float) -> float:
    """Retorna ρ: utilização média por servidor (a / c)."""
    if a < 0 or c <= 0:
        raise ValueError("'a' deve ser >= 0 e 'c' > 0.")
    return a / c

def calcular_wq(a: float, c: float, mu: float) -> float:
    """Retorna Wq: tempo médio de espera na fila."""
    if a < 0 or c <= 0 or mu <= 0:
        raise ValueError("'a' >= 0, 'c' > 0, 'mu' > 0.")
    if a >= c:
        raise ValueError("Sistema instável: 'a' deve ser < 'c'.")
    p_wait = erlang_c(a, c)
    return p_wait / (mu * (c - a))

def calcular_lq(a: float, c: float, mu: float) -> float:
    """Retorna Lq: número médio de clientes na fila."""
    return a * calcular_wq(a, c, mu)

def calcular_w(a: float, c: float, mu: float) -> float:
    """Retorna W: tempo médio no sistema (fila + atendimento)."""
    return calcular_wq(a, c, mu) + 1 / mu

def calcular_l(a: float, c: float, mu: float) -> float:
    """Retorna L: número médio de clientes no sistema (fila + atendimento)."""
    return a * calcular_w(a, c, mu)

def ler_float(msg: str) -> float:
    while True:
        try:
            return float(input(msg).replace(',', '.'))
        except ValueError:
            print('Valor inválido. Tente novamente.')

def ler_int(msg: str) -> int:
    while True:
        try:
            v = int(input(msg))
            if v <= 0:
                print('Digite um inteiro > 0.')
            else:
                return v
        except ValueError:
            print('Valor inválido. Tente novamente.')

def main():
    print('\n=== Calculadora Erlang C (P(wait)) ===')
    print('1) Entrar com a = λ/μ (Erlangs) e c')
    print('2) Entrar com λ, μ e c')
    opc = input('Escolha (1/2): ').strip()

    if opc == '1':
        a = ler_float('Informe a (λ/μ) em Erlangs: ')
        c = ler_int('Informe c (nº de servidores): ')
        if a <= 0:
            print('a deve ser > 0. Encerrando.')
            return
        p = erlang_c(a, c)
        ro = calcular_ro(a, c)
        print(f'ρ = {ro:.6f}')
    elif opc == '2':
        lam = ler_float('Informe λ (taxa de chegadas): ')
        mu = ler_float('Informe μ (taxa de atendimento por servidor): ')
        c = ler_int('Informe c (nº de servidores): ')
        if mu <= 0:
            print('μ deve ser > 0. Encerrando.')
            return
        a = lam / mu
        print(f'a = λ/μ = {a:.6f} Erlangs')
        p = erlang_c(a, c)
        ro = calcular_ro(a, c)
        wq = calcular_wq(a, c, mu)
        lq = calcular_lq(a, c, mu)
        w = calcular_w(a, c, mu)
        l = calcular_l(a, c, mu)
        print(f'ρ = {ro:.6f}')
        print(f'Wq = {wq:.6f}')
        print(f'Lq = {lq:.6f}')
        print(f'W  = {w:.6f}')
        print(f'L  = {l:.6f}')
    else:
        print('Opção inválida. Encerrando.')
        return

    print(f'\nP(wait) = {p:.6f}  (equivalente a {p*100:.2f}%)')
    if a >= c:
        print('Atenção: a ≥ c ⇒ sistema instável (fila explode).')
    else:
        print('Observação: estabilidade prática exige a < c.')

if __name__ == '__main__':
    while True:
        main()
        denovo = input('\nDeseja calcular novamente? (s/n): ').strip().lower()
        if denovo != 's':
            print('Encerrado.')
            break