USE EMPRESA;

SELECT F.Pnome AS 'NOME', 
	   F.Unome AS 'SOBRENOME', 
	   F.Salario AS 'SALARIO', 
	   CASE 
		WHEN Salario < 20000 THEN 'BAIXO'
		WHEN Salario BETWEEN 20000 AND 40000 THEN 'MEDIO'
		WHEN Salario > 40000 THEN 'ALTO'
		ELSE 'SEM REGISTRO'
	   END AS 'CATEGORIA'
FROM FUNCIONARIO AS F;

INSERT INTO FUNCIONARIO (Pnome, Unome, Minicial, Cpf, Data_Admissao) VALUES ('Genoveva', 'Thesc', 'H', '11122233345', '2025-09-09');

SELECT F.Pnome,
	   F.Data_Admissao,
	   CASE
		WHEN DATEDIFF(DAY, Data_Admissao, GETDATE()) <= 180 THEN 'SIM'
		ELSE 'NAO'
	   END AS 'CONTRATADO NOS ULTIMOS 6 MESES'
FROM FUNCIONARIO AS F;

UPDATE FUNCIONARIO SET Salario = 30000 WHERE FUNCIONARIO.Pnome = 'Carlos';

SELECT * FROM FUNCIONARIO;

BEGIN TRAN;
DECLARE @registroAfetado int = 0;
UPDATE FUNCIONARIO
SET Salario = 30000
WHERE Pnome = 'Carlos'
SET @registroAfetado = @@ROWCOUNT + @registroAfetado;

IF @registroAfetado <> 1
BEGIN
	ROLLBACK TRAN;
	PRINT 'ROLLBACK';
END;

ELSE
BEGIN
	COMMIT TRAN;
	PRINT 'COMMIT';
END

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRAN;
SELECT * FROM FUNCIONARIO
PRINT 'SELECT CONCLUIDO EM: ' + CONVERT(VARCHAR(30), SYSDATETIME(), 121);
-- PAUSA DE 20 SEC
WAITFOR DELAY '00:00:20'
COMMIT TRAN;
PRINT 'COMMIT EM: ' + CONVERT(VARCHAR(30), SYSDATETIME(), 121);

BEGIN TRAN;
INSERT INTO FUNCIONARIO (Pnome, Minicial, Unome, Cpf)
VALUES ('Herysson', 'R', 'Figueiredo', '81818181818')
PRINT 'INSERT CONCLUIDO EM: ' + CONVERT(VARCHAR(30), SYSDATETIME(), 121);
COMMIT TRAN;
PRINT 'COMMIT EM: ' + CONVERT(VARCHAR(30), SYSDATETIME(), 121);

BEGIN TRY
SELECT 1/0;
END TRY
BEGIN CATCH
PRINT 'NAO TEM COMO DIVIDIR';
PRINT 'NUMERO: ' + CAST(ERROR_NUMBER() AS VARCHAR(10));
PRINT 'ERRO: ' + ERROR_MESSAGE();
END CATCH

INSERT INTO DEPARTAMENTO (Dnome, Dnumero)
VALUES ('Marketing', 9); -- esse deu

BEGIN TRANSACTION;

INSERT INTO DEPARTAMENTO (Dnome, Dnumero)
VALUES ('Logística', 10); - esse nao

ROLLBACK TRAN;

--

BEGIN TRAN;


INSERT INTO DEPARTAMENTO (Dnome, Dnumero)
VALUES ('Jurídico', 11);

SAVE TRANSACTION Salva;

INSERT INTO DEPARTAMENTO (Dnome, Dnumero)
VALUES ('Auditoria', 12);

ROLLBACK TRAN Salva;

COMMIT TRAN;

--

BEGIN TRAN;

UPDATE FUNCIONARIO
SET Endereco = 'Rua Noia, 999, Sanga, RS'
WHERE Cpf = '98765432100';

SELECT Pnome, Unome, Endereco FROM FUNCIONARIO
WHERE Cpf = '98765432100';

-- ai ou commit ou rollback depende de ti