# -*- coding: utf-8 -*-
"""aula7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JTak8AxbpAwOm5kTdNMflVVNSY_Fwv3X
"""

import numpy as np
import matplotlib.pyplot as plt

def analisar_servico(nome, horario, servidores, chegadas, tempos_atendimento):
    total_chegadas = sum(chegadas)
    lambda_taxa = total_chegadas / 30  # chegadas por minuto
    tempo_medio = np.mean(tempos_atendimento)
    mu_taxa = 1 / tempo_medio           # atendimentos por minuto
    rho = lambda_taxa / (servidores * mu_taxa)

    if rho < 0.5:
        interpretacao = "Sistema SUBUTILIZADO"
        recomendacao = "pouca demanda"
    elif 0.5 <= rho < 0.8:
        interpretacao = "Sistema EFICIENTE"
        recomendacao = "funcionando bem"
    elif 0.8 <= rho < 1.0:
        interpretacao = "Sistema NO LIMITE"
        recomendacao = "aumento na demanda pode dar problema"
    else:
        interpretacao = "Sistema EM COLAPSO"
        recomendacao = "adicione mais servidores"

    print(f"\nANÁLISE DE FILAS - {nome}")
    print(f"Horário: {horario}")
    print("DADOS:")
    print(f"• Total de chegadas em 30 min: {total_chegadas} pessoas")
    print(f"• Número de servidores: {servidores}")
    print(f"• Tempo médio de atendimento: {tempo_medio:.2f} minutos")
    print("\nCÁLCULOS:")
    print(f"• λ (taxa de chegada): {lambda_taxa:.2f} pessoas/minuto")
    print(f"• μ (taxa de atendimento): {mu_taxa:.2f} atendimentos/minuto")
    print(f"• ρ (ocupação): {rho:.2f}")
    print("\nINTERPRETAÇÃO:")
    print(f"• {interpretacao}")
    print(f"• Recomendação: {recomendacao}")

    # Gráfico
    plt.figure(figsize=(10, 5))
    plt.plot(chegadas, label="Chegadas por minuto", marker="o")
    plt.plot(tempos_atendimento, label="Tempo de atendimento (min)", marker="x")
    plt.title(f"Chegadas e Atendimento - {nome}")
    plt.xlabel("Minuto da Observação")
    plt.ylabel("Valores")
    plt.legend()
    plt.grid(True)
    plt.show()


# ***** exemplos *****

# RU
chegadas_ru = [4,5,3,6,4,5,7,6,8,5,7,6,5,8,9,7,6,8,7,6,5,7,6,8,9,7,6,5,7,8]
tempos_ru = [2.1,1.9,2.0,2.2,1.8,2.0,2.1,1.9,2.3,2.0,
             2.1,2.2,1.9,2.0,2.1,2.0,2.3,2.2,1.9,2.0,
             2.1,2.0,1.9,2.2,2.1,2.0,2.2,2.3,2.0,2.1]
servidores_ru = 3

# Laboratório de Informática
chegadas_lab = [1,0,2,1,1,2,1,0,1,2,1,1,0,2,1,1,2,1,0,1,1,2,1,0,1,2,1,1,1,0]
tempos_lab = [15,14,16,15,13,14,15,16,14,15,
              15,14,16,15,13,14,15,16,14,15,
              15,14,16,15,13,14,15,16,14,15]
servidores_lab = 20  # máquinas disponíveis

# **** rodando ****
analisar_servico("RU da Faculdade", "12h às 12h30", servidores_ru, chegadas_ru, tempos_ru)
analisar_servico("Laboratório de Informática", "14h às 14h30", servidores_lab, chegadas_lab, tempos_lab)

#RU: O serviço não funciona bem, pois a demanda é muito maior que a capacidade de atendimento, causando filas crescentes e tempo de espera excessivo.

#Laboratório de Informática: O serviço funciona bem, pois há muitos computadores disponíveis em relação ao número de usuários, deixando o sistema subutilizado mas sem filas.